### ISSUE TITLE
cross-package type alias definitions have self-referencing semantic definition results

### ISSUE THREAD

**Issue by zephyrtronium** [sourcegraph/lsif-go#130]
Go To Definition on `sfnt.Font` in the definition of `opentype.Font` at https://sourcegraph.com/github.com/golang/image@35266b937fa6/-/blob/font/opentype/opentype.go#L67:6 goes to `opentype.Font`. I expected it to instead take me to the definition of `sfnt.Font`, which is in a different package in the same module.

**Comment by Strum355** [comment]
Hey Branden, thanks for filing the issue :slightly_smiling_face: we've solved this issue and will link the PR asap
