### ISSUE TITLE
Processor failing during CI/CD

### ISSUE THREAD

**Issue by emchap** [sourcegraph/lsif-go#133]
Customer reported as well, filed separately here: https://github.com/sourcegraph/customer/issues/216

The processor is failing during CI/CD; log are linked in the customer issue for privacy. Reverting to 1.2 resolves the issue. Top error:

`panic: interface conversion: types.Type is *types.Struct, not *types.Named`

@Strum355 reported that he found a public repo demonstrating the issue as well.

**Comment by Strum355** [comment]
Issue has been narrowed down to cases of type aliases to unnamed struct eg
```go
type Secret = struct { ... }
```
All personal gripes about this aside, this should be fast enough to fix. Thanks for the report :slightly_smiling_face:
