### ISSUE TITLE
Investigate support for generics in Go 1.18

### ISSUE THREAD

**Issue by mrnugget** [sourcegraph/lsif-go#240]
We should check if generics cause `lsif-go` to crash by testing it against existing package with generics.

**Comment by Strum355** [comment]
First round of investigation:

`lsif-go` does not panic on a codebase with generics, and the LSIF upload is succesful. 
And thats mostly where the good parts end.

The hover is mostly useless, and codeintel for the type and most of the rest of the file are not precise at all 
![image](https://user-images.githubusercontent.com/18282288/159985718-20374079-29e1-468b-8ed8-85ef425dacf6.png)

![image](https://user-images.githubusercontent.com/18282288/159985872-995c0061-28ff-4bc5-a4be-c3986a5e3e94.png)

**Comment by mrnugget** [comment]
Thanks! Do you plan to do another "round of investigation" in this iteration? If so, feel free to re-open, because I'm closing this now since we got what we wanted.
