### ISSUE TITLE
What about a golang version of LSIF server?

### ISSUE THREAD

**Issue by xingx-xx** [sourcegraph/lsif-go#26]
I read some blogs for LSIF protocol recently, but I only found LSIF servers written in typescript.
Is there any plan to write a golang version of server to serve the LSIF dumps?

**Comment by unknwon** [comment]
I think @efritz has the most knowledge about this topic.

**Comment by efritz** [comment]
Our LSIF server can be found in our [main repo](https://github.com/sourcegraph/sourcegraph/tree/master/lsif). It's written in TypeScript as it originally relied heavily on code from the VS Code LSIF extension, which was also in TypeScript.

What is your use-case for an LSIF server, and why does the language matter?

**Comment by xingx-xx** [comment]
> Our LSIF server can be found in our [main repo](https://github.com/sourcegraph/sourcegraph/tree/master/lsif). It's written in TypeScript as it originally relied heavily on code from the VS Code LSIF extension, which was also in TypeScript.
> 
> What is your use-case for an LSIF server, and why does the language matter?

Thanks for your reply! I learned a lot from your LSIF related code. Typescript is good but in my case the backend servers are all written in go and none of my mates is proficient in typescript. :-)

In fact we wanna integrate LSIF(or something alike) to provide code intelligence for our codebase, but we must find some good solutions to handle issues like incremental index generation, per commit index storage.

Per commit LSIF dump generation can be slow and the storage can be huge, but per commit code intelligence seems necessary in cases like pull request and commit comparison. Are you working on these scenarios and do you have some suggestions?

**Comment by unknwon** [comment]
@xingx-xx We internally had discussion about incremental index generation for about a week, and decide to not go down that path due to complexity. Instead, @efritz is now working on https://github.com/sourcegraph/sourcegraph/pull/5691, if I understand correctly, when the LSIF data is not available for the desired commit, it tries to find its closet commit with LSIF data.

**Comment by efritz** [comment]
Closing as non-actionable. Let us know if you have more questions - LSIF is still bleeding edge at this point!
