### ISSUE TITLE
Feature request: Support for other build systems

### ISSUE THREAD

**Issue by Tatskaari** [sourcegraph/lsif-go#261]
Hey! We use [Please](https://please.build), which means that we don't have a `go.mod` in the root of our repo. Unfortunately this tool assumes that it can use `go list` and other `go build` specific commands during initialisation. Other users might be using Bazel or similar, and will encounter similar problems, where these commands won't necessarily work as expected or at all. 

Fortunately, `golang.org/x/tools/go/packages` supports plugging in a different "go list driver" ([example](https://github.com/bazelbuild/rules_go/wiki/Editor-and-tool-integration#driver-interface)), so in theory, the indexer should be able to glean all the information it needs. This tool likely would need to be re-worked so that it doesn't require as much information up front about the "module" and it's dependencies, as it may not be indexing a module.

**Comment by tjdevries** [comment]
Hi @Tatskaari thanks for reaching out! I'm actually in the process of a rewrite of the tool here: https://github.com/sourcegraph/scip-go

Would you mind opening an issue there where we could talk about this? I'd be very interested to explore how we could support alternate build systems for `scip-go`.

**Comment by Tatskaari** [comment]
Okay sure thing! I'll re-open there.

**Comment by tjdevries** [comment]
I do work there :) i'll see if I can get that figured out how to join. thanks!
