### ISSUE TITLE
No LSIF data dumped for test files?

### ISSUE THREAD

**Issue by blanet** [sourcegraph/lsif-go#27]
LSIF dumps for test files should be generated and now they are missing.

Maybe Using `golang.org/x/tools/go/packages` is not the best way to dump LSIF considering generation speed and idempotent. But for now I have no idea how to improve this either. ;-)

**Comment by efritz** [comment]
This looks like it was fixed in https://github.com/sourcegraph/lsif-go/commit/0e6f7dd01a88c649a0f5dc58bdead2a24a1dd2bc.
