### ISSUE TITLE
inVs is null

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/lsif-go#4]
In the dump of gorilla/mux, there is an edge
```js
{
  id: '12458',
  type: 'edge',
  label: 'contains',
  outV: '96',
  inVs: null
}
```
this is invalid, `inVs` should be an empty array or this edge should not be included.

**Comment by felixfbecker** [comment]
This still happens with

Go LSIF exporter: 0.2.0
Protocol version: 0.4.0

**Comment by felixfbecker** [comment]
I would recommend validating the output against https://github.com/sourcegraph/sourcegraph/blob/lsif-dgraph/lsif/server/src/lsif.schema.json

(with anyOf: [Vertex, Edge])

**Comment by unknwon** [comment]
Which commit your lsif-go is built with? If you're unsure, would you mind do another `git pull` and rebuild the binary, I just changed the version output in the `master` to be `0.3.0`.

```
➜ lsif-go version
Go LSIF exporter: 0.3.0
Protocol version: 0.4.0
```

**Comment by felixfbecker** [comment]
I used `go get -u`. It's 0.3.0 now

**Comment by unknwon** [comment]
The LSIF dump generated from https://github.com/gorilla/mux/tree/e67b3c02c7195c052acff13261f0c9fd1ba53011 has 11560 lines, and I'm not able to find `null` or `"inVs":[]`, I wonder what kind of values will be converted to `null` in the JS-end?

**Comment by felixfbecker** [comment]
Hmm I tried to repro again and this time didn't get any nulls. Probably had an old version.

Btw, would be great if you could `git tag` releases :)
