### ISSUE TITLE
Improve handling of repositories with no go.mod file

### ISSUE THREAD

**Issue by creachadair** [sourcegraph/lsif-go#55]
The indexer currently requires a `go.mod` file to be present in the repository. It does not need to be at the root (the `--moduleRoot` flag allows a subdirectory). If there is none, however, dependency resolution will not work.

Although Go packages without a module are increasingly rare, they still occur in the wild. One way to handle such repositories better would be to create a temporary `go.mod` file during indexing: Using the remote URL and/or canonical import path comments in the source files, the indexer could create a stub `go.mod` file and populate it (as by `go mod tidy`) before attempting to index. To avoid polluting a local build, this would probably need to be virtualized through the build package's VFS hooks or maybe a temp directory wrapper.

The first step is to figure out whether this situation happens often enough to be worth fixing.

**Comment by aidaeology** [comment]
This issue seems to outline the same problem - not sure we would want to take the path described:
https://github.com/sourcegraph/lsif-go/issues/55
