### ISSUE TITLE
lsif-go fails for mysterious reasons on sourcegraph/resource-estimator

### ISSUE THREAD

**Issue by gbrik** [sourcegraph/lsif-go#62]
What currently happens:
```
$ git clone https://github.com/sourcegraph/resource-estimator
$ cd resource-estimator
$ lsif-go
error: fetching dependencies: exit status 1
```
cc @sourcegraph/code-intel

**Comment by efritz** [comment]
Some things to look in to (in general, not just this repo):

- does it not have a go.mod file
- does it have something like glide.yaml
- does go mod vendor fail

**Comment by efritz** [comment]
`go mod download` is what I think this error is coming from.

**Comment by gbrik** [comment]
looked a bit more, this is due to the `go.mod` including a dependency from local source tree which wasn't documented
