### ISSUE TITLE
Missing reference (calls of searchCommitLogInRepo)

### ISSUE THREAD

**Issue by rvantonder** [sourcegraph/lsif-go#65]
This is not urgent, just flagging for visibility. Feel free to reassign or unassign. Looks like we may miss some references.

I was surprised that find reference of `searchCommitLogInRepo` didn't turn up anything. Find references shows me this:

![Screen Shot 2020-07-24 at 4 47 45 PM](https://user-images.githubusercontent.com/888624/88443508-6f72b680-cdcd-11ea-9f02-b52dc1006d3d.png)

When I search for `searchCommitLogInRepo`, it shows a caller in the function `searchCommitLogInRepos` (note the **s** there). The caller is in the same file:

![Screen Shot 2020-07-24 at 4 48 40 PM](https://user-images.githubusercontent.com/888624/88443539-8dd8b200-cdcd-11ea-8330-c48905c514cf.png)

Not sure why that call is not picked up as a reference. The Go-to-definition on that call works, so it's almost like the references edge is missing.

**Comment by efritz** [comment]
@rvantonder I think I see what's going on there, but can you confirm if the behavior is still happening? I think it's been straightened out after some changes on the way to v1.0.

https://sourcegraph.com/github.com/sourcegraph/sourcegraph@005101b80bcfd36cb6a2bb7f43f48f484e16a63c/-/blob/cmd/frontend/graphqlbackend/search_commits.go#L82:6&tab=references

**Comment by tjdevries** [comment]
I'm just thinking this is probably fixed because gigafritz said so
